#------------- VERSION -------------#
version: '3'
services:
  hill-climbing:
    build: .
    tty: true
    stdin_open: true
    image: hill-climbing
    deploy:
      replicas: 4
    #container_name: hill-climbing
    volumes:
      - ./hill-climbing:/app
  
  abstaylor:
    build: .
    tty: true
    stdin_open: true
    image: abstaylor
    deploy:
      replicas: 3
    #container_name: abstaylor
    volumes:
      - ./abstaylor:/app

  simulated-annealing:
    build: .
    tty: true
    stdin_open: true
    image: simulated-annealing
    container_name: simulated-annealing
    volumes:
      - ./simulated-annealing:/app

  # dual-annealing:
  #   build: 
  #     context: .
  #     dockerfile: DA.Dockerfile
  #   tty: true
  #   stdin_open: true
  #   image: dual-annealing
  #   container_name: dual-annealing
  #   volumes:
  #     - ./dual-annealing:/f1/app
  #     - ./da:/f2/app